

services:
  cruciverba-app:
    build: 
      context: .
      args:
        - BUILDKIT_INLINE_CACHE=0
    image: crucibia-cruciverba-app
    container_name: cruciverba-bianca
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 